services:
  - type: web
    name: gameon-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false # Set this in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Set this in Render dashboard (if using Cloudinary)
      - key: CLOUDINARY_API_KEY
        sync: false # Set this in Render dashboard (if using Cloudinary)
      - key: CLOUDINARY_API_SECRET
        sync: false # Set this in Render dashboard (if using Cloudinary)
      - key: RAZORPAY_KEY_ID
        sync: false # Set this in Render dashboard (if using Razorpay)
      - key: RAZORPAY_KEY_SECRET
        sync: false # Set this in Render dashboard (if using Razorpay)